# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Rust/Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "UTC"
    # Group all patch and minor updates into a single PR
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
    # Limit the number of open PRs
    open-pull-requests-limit: 5
    # Add reviewers (optional - replace with your GitHub username)
    # reviewers:
    #   - "raykrueger"
    # Add labels to PRs
    labels:
      - "dependencies"
      - "dependabot"
      - "auto-merge"
    # Commit message configuration
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Allow Dependabot to rebase PRs when conflicts occur
    rebase-strategy: "auto"
    # Target branch
    target-branch: "main"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    # Group all GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "github-actions"
      - "dependabot"
      - "auto-merge"
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"
    target-branch: "main"
