name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Auto-approve and enable auto-merge
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            
            console.log(`Processing Dependabot PR #${pr.number}: ${pr.title}`);
            
            // Auto-approve the PR
            try {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                event: 'APPROVE',
                body: '🤖 Auto-approving Dependabot PR'
              });
              console.log('✅ PR approved');
            } catch (error) {
              console.log('ℹ️ PR may already be approved:', error.message);
            }
            
            // Enable auto-merge
            try {
              await github.rest.pulls.updateBranch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number
              });
              
              await github.rest.graphql(`
                mutation($pullRequestId: ID!) {
                  enablePullRequestAutoMerge(input: {
                    pullRequestId: $pullRequestId,
                    mergeMethod: SQUASH
                  }) {
                    pullRequest {
                      autoMergeRequest {
                        enabledAt
                      }
                    }
                  }
                }
              `, {
                pullRequestId: pr.node_id
              });
              
              console.log('✅ Auto-merge enabled');
              
              // Add informative comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `🤖 **Auto-merge enabled**
                
                This Dependabot PR has been automatically approved and will merge when all checks pass.
                
                **Status**: ⏳ Waiting for required status checks
                **Merge method**: Squash and merge
                
                To disable auto-merge, comment: \`@dependabot cancel merge\``
              });
              
            } catch (error) {
              console.error('❌ Failed to enable auto-merge:', error.message);
              
              // Fallback comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `🤖 **Auto-merge attempted**
                
                This Dependabot PR has been approved, but auto-merge could not be enabled automatically.
                
                You can enable it manually by commenting: \`@dependabot squash and merge\`
                
                Or merge manually when all checks pass.`
              });
            }
